### ISSUE TITLE
与 Laravel 相比有什么优势吗？

### ISSUE THREAD

**Issue by Gwill** [hfcorriez/pagon#12]
与 Laravel 相比有什么优势吗？

**Comment by hfcorriez** [comment]
Laravel的核心在于丰富和快速开发

1 完善的底层，强大的核心，丰富的支撑
2 完全静态的写法，开发快速上手
3 社会有很多插件
4 几近完美的应用模型
5 模块继承和独立

个人也蛮喜欢Laravel的。
Pagon的核心我在另外一个issue解释过了。Pagon也会参考各种框架的优点。
所以，不管是Laravel，Slim，Express都是很好的框架，重在怎么去使用它们。
