### ISSUE TITLE
与 Slim 相比有什么优势吗？

### ISSUE THREAD

**Issue by Gwill** [hfcorriez/pagon#13]
与 Slim 相比有什么优势吗？

**Comment by hfcorriez** [comment]
Slim的核心在于精简

1 精简到只有一个核心，自由度很高
2 中间件模式
3 只提供HTTP，维护简单

Pagon的核心在于为现代应用打造：

1 会有精简版本，只有一个核心，自由度也很高。甚至会有极简的单文件版本。
2 中间件模式
3 HTTP和CLI模式都能支持，对现代应用开发提供便利
4 所有对象皆有事件，所有对象皆可注入，最高的自由度。
5 注重应用性能
6 提供应用模型，可快速开发应用
