### ISSUE TITLE
how to getstarted with phpstudy

### ISSUE THREAD

**Issue by yolio2003** [hfcorriez/pagon#14]
phpstudy 如何安装 composer，以引用 pagon
看到除了pagon 又有啦pagon core, pagon framework, logger等
我想安装一个全的，且方便以后升级pagon新版该怎么做

**Comment by hfcorriez** [comment]
第一个问题已经在 sf 回答你了。官方教程比较明白。

然后，你只需要 git 拉取最新的 pagon 就行了，获取使用 composer create-project 来安装。在目前版本，pagon 成为一个脚手架，只需要知道 pagon 就行了。pagon 会使用 composer 来管理依赖。如果要更新，大多是 composer update 即可。

解释下几个库的功能区分：

pagon        脚手架，可以直接拿来用的
framework 就是框架，封装了框架的功能
core           就是框架的核心，最小化的可运行部分
logger        日志库
cli               服务于 pagon 的命令行
其它的...    被依赖的或提供辅助功能的库
